version: '3.5'

services:
  helk-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: helk-elasticsearch
    secrets:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./helk-elasticsearch/scripts:/usr/share/elasticsearch/scripts
    entrypoint: /usr/share/elasticsearch/scripts/elasticsearch-entrypoint.sh
    environment:
      - cluster.name=helk-cluster
      - node.name=helk-1
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    networks:
      helk:
  helk-logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    container_name: helk-logstash
    secrets:
      - source: logstash.yml
        target: /usr/share/logstash/config/logstash.yml
    volumes:
      - ./helk-logstash/pipeline:/usr/share/logstash/pipeline
      - ./helk-logstash/output_templates:/usr/share/logstash/output_templates
      - ./helk-logstash/enrichments/cti:/usr/share/logstash/cti
      - ./helk-logstash/scripts:/usr/share/logstash/scripts
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    entrypoint: /usr/share/logstash/scripts/logstash-entrypoint.sh
    ports:
      - "5044:5044"
    restart: always
    depends_on:
      - helk-zookeeper
    networks:
      helk:
  helk-kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: helk-kibana
    secrets:
      - source: kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - ./helk-kibana/dashboards:/usr/share/kibana/dashboards
      - ./helk-kibana/scripts:/usr/share/kibana/scripts
    entrypoint: /usr/share/kibana/scripts/kibana-entrypoint.sh
    restart: always
    depends_on:
      - helk-elasticsearch
    networks:
      helk:
  helk-nginx:
    image: cyb3rward0g/helk-nginx:0.0.7
    container_name: helk-nginx
    secrets:
      - source: htpasswd.users
        target: /etc/nginx/htpasswd.users
    volumes:
      - ./helk-nginx/default:/etc/nginx/sites-available/default
      - ./helk-nginx/scripts/:/opt/helk/scripts/
    entrypoint: /opt/helk/scripts/nginx-entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - helk-kibana
      - helk-jupyter
    networks:
      helk:
  helk-jupyter:
    image: cyb3rward0g/helk-jupyter:0.0.5
    container_name: helk-jupyter
    restart: always
    depends_on:
      - helk-elasticsearch
    networks:
      helk:
  helk-spark-master:
    image: cyb3rward0g/helk-spark-master:2.3.1-b
    container_name: helk-spark-master
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - helk-elasticsearch
    networks:
      helk:
  helk-spark-worker:
    image: cyb3rward0g/helk-spark-worker:2.3.1-b
    container_name: helk-spark-worker
    environment:
      - SPARK_MASTER=spark://helk-spark-master:7077
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_PORT=42950
    restart: always
    depends_on:
      - helk-spark-master
    networks:
      helk:
  helk-spark-worker2:
    image: cyb3rward0g/helk-spark-worker:2.3.1-b
    container_name: helk-spark-worker2
    environment:
      - SPARK_MASTER=spark://helk-spark-master:7077
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_PORT=42951
    restart: always
    depends_on:
      - helk-spark-master
    networks:
      helk:
  helk-zookeeper:
    image: cyb3rward0g/helk-zookeeper:2.0.0-a
    container_name: helk-zookeeper
    ports:
      - "2181:2181"
    restart: always
    depends_on:
      - helk-kibana
    networks:
      helk:
  helk-kafka-broker:
    image: cyb3rward0g/helk-kafka-broker:2.0.0-b
    container_name: helk-kafka-broker
    restart: always
    depends_on:
      - helk-zookeeper
    environment:
      - KAFKA_BROKER_NAME=helk-kafka-broker
      - KAFKA_BROKER_ID=1
      - KAFKA_BROKER_PORT=9092
      - REPLICATION_FACTOR=2
      - ADVERTISED_LISTENER=HOSTIP
      - ZOOKEEPER_NAME=helk-zookeeper
      - KAFKA_CREATE_TOPICS=True
    ports:
      - "9092:9092"
    networks:
      helk:
  helk-kafka-broker2:
    image: cyb3rward0g/helk-kafka-broker:2.0.0-b
    container_name: helk-kafka-broker2
    restart: always
    depends_on:
      - helk-zookeeper
    environment:
      - KAFKA_BROKER_NAME=helk-kafka-broker2
      - KAFKA_BROKER_ID=2
      - KAFKA_BROKER_PORT=9093
      - REPLICATION_FACTOR=2
      - ADVERTISED_LISTENER=HOSTIP
      - ZOOKEEPER_NAME=helk-zookeeper
      - KAFKA_CREATE_TOPICS=True
    ports:
      - "9093:9093"
    networks:
      helk:

networks:
  helk:
    driver: bridge

volumes:
  esdata:
    driver: local

secrets:
  elasticsearch.yml:
    file: ./helk-elasticsearch/elasticsearch.yml
  logstash.yml:
    file: ./helk-logstash/logstash.yml
  kibana.yml:
    file: ./helk-kibana/kibana.yml
  htpasswd.users:
    file: ./helk-nginx/htpasswd.users