# HELK Custom
pipeline.batch.size: 500
config.reload.automatic: false
config.reload.interval: 60s
pipeline.ordered: false
# Following variables and values be set at docker runtime
#pipeline.workers: 2
#xpack.monitoring.elasticsearch.hosts: http://helk-elasticsearch:9200
#log.level: warn
#http.host: "0.0.0.0"
#xpack.monitoring.enabled: true